language: android
jdk: oraclejdk8
sudo: required
#https://medium.com/@harmittaa/travis-ci-android-example-357f6e632fc4

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

env:
 global:
 - ANDROID_API=28
 - MIN_API=17
 - ANDROID_BUILD_TOOLS=26.0.2
 - ADB_INSTALL_TIMEOUT=5 # minutes

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS

    # The SDK version used to compile your project
    - android-$ANDROID_API
    - android-$MIN_LEVEL

    # Additional components
    - extra-android-m2repository
    - addon-google_apis-google-26
 


    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-$ANDROID_API
    - sys-img-armeabi-v7a-android-$MIN_API
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+    

# whitelist
branches:
  only:
  - master
  - stable


before_install:
    - chmod +x gradlew

before_script:
    - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &


#TODO: add commented lines
script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"
#./gradlew clean androidDependencies     
#./gradlew clean lint
#./gradlew clean test
#./gradlew clean assembleDebug


#TODO
#before_deploy:
#- cp $TRAVIS_BUILD_DIR/.keystore $HOME
#- cd app/build/outputs/apk/
#- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/keystore.jks -storepass $storepass -keypass $keypass app-release-unsigned.apk yourapp_keystore
#
## Verification
#- jarsigner -verify app-release-unsigned.apk
#- "${ANDROID_HOME}/build-tools/24.0.2/zipalign -v 4 app-release-unsigned.apk yourapp.apk"
#
#
#deploy:
#  provider: releases
#  file: yourapp.apk
#  skip_cleanup: true
#  on:
#    repo: githubUsername/Repository
#    tags: true
#    jdk: oraclejdk8
#  api_key:
#    secure: here goes the encrypted api key