language: android
jdk: oraclejdk8
sudo: false
#https://medium.com/@harmittaa/travis-ci-android-example-357f6e632fc4

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

env:
 global:
 - ANDROID_API=26
 - MIN_API=17
 - ANDROID_BUILD_TOOLS=26.0.2
 - ADB_INSTALL_TIMEOUT=5 # minutes

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-27.0.3

    # The SDK version used to compile your project
    - android-28

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-26
    - sys-img-armeabi-v7a-android-28

    # Additional components
    - extra-android-m2repository
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

# whitelist
branches:
  only:
  - master
  - travisCI-testcases



before_script:
    - sudo chmod +x ./gradlew
    - yes | sudo sdkmanager --licenses


#TODO: fix this
#before_script:
#    - echo no | android create avd --force -n test -t android-26 --abi armeabi-v7a
#    - emulator -avd test -no-skin -no-audio -no-window &
#    - android-wait-for-emulator
#    - adb shell input keyevent 82 &


#TODO
script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - ./gradlew clean androidDependencies
    - ./gradlew clean test
    - ./gradlew clean build
#    - ./gradlew build testDebug --stacktrace

